name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --output "type=image,push=${{ steps.detect.outputs.push }}" \
            --progress=plain \
            --tag ghcr.io/pyplanet:$(date +%s) \
          .
